# Generated by Django 4.1.7 on 2023-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.CharField(editable=False, max_length=13, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=16)),
                ('prenom', models.CharField(max_length=16)),
            ],
        ),
    ]
