# Generated by Django 4.1.7 on 2023-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.AddField(
            model_name='personnel',
            name='num_secu',
            field=models.CharField(default=0, max_length=13, primary_key=True, serialize=False),
        ),
    ]
