# Generated by Django 4.2.1 on 2023-05-12 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme - Employé'), ('Femme', 'Femme - Employée'), ('Inconnu', 'Inconnu - ?')], default='Inconnu', max_length=7),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 14, 39, 56, 165050)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=32),
        ),
    ]
