# Generated by Django 4.2.1 on 2023-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0014_personnel_sexe_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='etat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Utilise Windows 11'), ('Mac', 'Mac - Utilise MacOS'), ('Serveur', 'Serveur - Serveur pour déployer des VM'), ('Switch', 'Switch - Maintient et connect des serveurs')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default='2023-05-12'),
        ),
    ]
