# Generated by Django 4.2.1 on 2023-05-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0015_machine_etat_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='etat',
        ),
    ]
