# Generated by Django 4.2.1 on 2023-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0016_remove_machine_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
