# Generated by Django 4.2.1 on 2023-05-16 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0018_alter_machine_maintenancedate_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='infra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='computerApp.infrastructure'),
        ),
    ]
