# Generated by Django 4.2.1 on 2023-05-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0019_machine_infra'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='usage_percentage',
            field=models.FloatField(default=0),
        ),
    ]
